name: artist
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.7+7

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  page_transition: ^2.1.0
  permission_handler: ^11.3.0
  fluttertoast: ^8.2.2
  curved_navigation_bar: ^1.0.6
  pinput: ^5.0.0
  intl_phone_number_input: ^0.7.4
  google_fonts: ^6.2.1
  flutter_staggered_animations: ^1.1.1
  animated_list_item: ^1.0.0
  flutter_staggered_grid_view: ^0.4.0
  shared_preferences: ^2.2.2
  http: ^1.3.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  screenshot: ^3.0.0
  intl: ^0.19.0
  geolocator: ^13.0.2
  qr_flutter: ^4.1.0
  timeago: ^3.6.0
  url_launcher: ^6.3.1
  path: ^1.8.3
  flutter_image_compress: ^1.1.1
  flutter_rating_bar: ^4.0.1
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  flutter_local_notifications: ^18.0.1
  flutter_stripe: ^11.4.0
  scroll_loop_auto_scroll: ^0.0.5
  fl_chart: ^0.67.0
  file_picker: ^5.0.0
  open_filex: ^4.6.0
  archive: ^4.0.3
  connectivity_plus: ^6.1.3
  firebase_database:
  flutter_launcher_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_final.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo_final.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo_final.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo_final.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images2/
    - assets/onboarding/
    - assets/bottom_navigation_bar_icon/
    - assets/profile_image/
    - assets/artist/
    - assets/artist/upload_page/
